language: go # skip default ruby installs, use docker images

services:
  - docker

branches:
  only:
  - master

before_install:
 - docker-compose build
 - docker-compose run -T -e RAILS_ENV=test --rm --entrypoint="bundle exec rake db:create" education

script:
  - docker-compose run -T -e RAILS_ENV=test --rm --entrypoint="bundle exec rspec" education