services:
  - docker

branches:
  only:
  - master

before_install:
 - docker-compose build
 - docker-compose run -T -e RAILS_ENV=test --rm --entrypoint="bundle exec rake db:create" education

install: # skip the ruby bundler install,
         # https://docs.travis-ci.com/user/languages/ruby/#default-build-script

script:
  - docker-compose run -T -e RAILS_ENV=test --rm --entrypoint="bundle exec rspec" education