postgres:
  image: postgres
  environment:
    - "POSTGRES_USER=education"
    - "POSTGRES_PASSWORD=education"
  ports:
    - "5432:5432"

redis:
  image: redis
  command: redis-server --appendonly yes

education:
  dockerfile: Dockerfile
  build: ./
  volumes:
    - ./:/app
  ports:
    - "3000:3000"
  environment:
    - "RAILS_ENV=development"
    - "REDIS_URL=redis://redis:6379"
    - "POSTGRES_HOSTNAME=pg"
    - "POSTGRES_USERNAME=education"
    - "POSTGRES_PASSWORD=education"
    - "SIDEKIQ_USERNAME=education"
    - "SIDEKIQ_PASSWORD=education"
  links:
    - postgres:pg
    - redis:redis
