---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: education-api-production-redis
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: education-api-production-redis
  labels:
    app: education-api-production-redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: education-api-production-redis
  template:
    metadata:
      labels:
        app: education-api-production-redis
    spec:
      containers:
        - name: education-api-production-redis
          image: redis
          volumeMounts:
          - name: education-api-production-redis-data
            mountPath: "/data"
      volumes:
      - name: education-api-production-redis-data
        persistentVolumeClaim:
          claimName: education-api-production-redis
---
apiVersion: v1
kind: Service
metadata:
  name: education-api-production-redis
spec:
  selector:
    app: education-api-production-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: NodePort
