name: Build and Push Image

on:
  pull_request:
  workflow_dispatch:

jobs:
  build_and_push_image:
    name: Build and Push Image
    uses: zooniverse/ci-cd/.github/workflows/build_and_push_image.yaml@main
    with:
      repo_name: education-api
      commit_id: ${{ github.sha }}

