name: Staging DB Migration

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  db_migration_staging:
    name: Staging DB Migration
    uses: zooniverse/ci-cd/.github/workflows/db_migration.yaml@main
    with:
      app_name: education-api
      environment: staging
    secrets:
      creds: ${{ secrets.AZURE_AKS }}

  slack_notification:
    name: Slack notification
    uses: zooniverse/ci-cd/.github/workflows/slack_notification.yaml@main
    needs: db_migration_staging
    if: always()
    with:
      commit_id: ${{ github.sha }}
      job_name: Staging DB Migration / db_migration_staging
      status: ${{ needs.db_migration_staging.result }}
      title: "Education API Staging database migration complete"
      title_link: "https://education-api-staging.zooniverse.org"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
